### PR TITLE
KIALI-2011 fix strange hover in documentation link

### PR DESCRIPTION
**Pull request by abonas**
After the fix the link color is changed, but the size remains the same - which fixes the strange hover issue.
afterfix

### CODE REVIEW

**Comment by theute** [comment]
While it fixer the issue, now the top menu font size changed and going to Documentation>Glossary>Observability, the menu items grow in size when hovered

**Comment by abonas** [comment]
> While it fixer the issue, now the top menu font size changed and going to Documentation>Glossary>Observability, the menu items grow in size when hovered

I changed the top menu font size to be bigger anyway, the Documentation->Glossary->Observability was not working prior to the fix as well, but I'll see how to fix that one too.

**Comment by abonas** [comment]
@theute the issue with secondary menu size is now solved

**Comment by mtho11** [comment]
I'll let @theute push the green button if he approves

**Pull request merged**
