### PR TITLE
Enhance video sections to be more like blog section.

### PR DESCRIPTION
**Pull request by mtho11**

### CODE REVIEW

**Comment by mtho11** [comment]
I just did it for the Latest Videos section to get approval 

video-scroll

**Comment by mtho11** [comment]
@jshaughn @lucasponce  WDYT?

**Comment by lucasponce** [comment]
The idea of the scroll is good.

But the horizontal space between videos is not same as the blogs/events cards.

Also the fonts used and icon looks different than the cards, perhaps if those can be align as well it would look closer.

From the Blog list:
image

From the Event list:
image

**Comment by mtho11** [comment]
Ok, I think I have managed to make all the style changes consistent:

latest-videos2

**Comment by lucasponce** [comment]
> LGTM. Not a blocker for me but if you can left-align align the Blogs and the Events sections with the videos that would be even nicer.

+1

**Comment by lucasponce** [comment]
I've merged to progress but I couldn't test locally.

image

I've realized that at the moment we use a wide resolution, the kiali.io starts to look bad.

@mtho11 would you mind to send a followup fix for this ?

**Comment by mtho11** [comment]
@lucasponce following up on fix

**Comment by mtho11** [comment]
Looks like we also need a fix for the features section as it doesn't align as well...

Kiali__Service_mesh_observability_and_configuration

Someone want to tackle that one?

**Comment by israel-hdez** [comment]
The features card are supposed to be centered on the page.

Indeed, everything is supposed to be centered on the page. It's just that widths vary and some blocks have same with.

**Comment by mtho11** [comment]
Ah ok, thanks @israel-hdez

**Pull request merged**
