### PR TITLE
update KIA0207 example

### PR DESCRIPTION
**Pull request by zirain**
policy is no longer exists in istio, update the demo with PeerAuthentication

### CODE REVIEW

**Review by jmazzitelli — CHANGES_REQUESTED** [review]
There is no github issue associated with this PR. In addition, there are no details -- what is the problem you are seeing? How do you reproduce the problem? What version of Kiali? What version of Istio? etc. etc.

Prior to submitting a PR, please submit a github issue explaining the problem, as per the community contribution guidelines specified here: https://github.com/kiali/kiali/blob/master/CONTRIBUTING.md#making-a-change

**Comment by jshaughn** [comment]
@zirain , please re-open the PR if it's valid for the currently supported versions of Istio.  We just wanted to make sure it was applicable to all of the Istio versions supported by the latest version of Kiali.

**Comment by zirain** [comment]
> @zirain , please re-open the PR if it's valid for the currently supported versions of Istio. We just wanted to make sure it was applicable to all of the Istio versions supported by the latest version of Kiali.

I'm pretty sure that policy is no long valid for a long time.

**Comment by jshaughn** [comment]
cc @hhovsepy

**Comment by hhovsepy** [comment]
thanks @zirain for the catch, I confirm that the docs were outdated with KIA0207

**Pull request merged**
