### PR TITLE
Added table of contents to the README file

### PR DESCRIPTION
**Pull request by josunect**

### CODE REVIEW

**Review by aljesusg — APPROVED** [review]
LGFM

**Comment by aljesusg** [comment]
Cc @lucasponce

**Comment by jshaughn** [comment]
@josunect , was that your first PR merge?  Congrats!

As an aside, it helps for github project queries if you set yourself as 'Assignee', and also set a Project.

**Comment by josunect** [comment]
> @josunect , was that your first PR merge? Congrats!
> 
> As an aside, it helps for github project queries if you set yourself as 'Assignee', and also set a Project.

Thanks, @jshaughn , notes taken for the next PR!

**Pull request merged**
