### PR TITLE
Fixo typo in upgrade Kiali section

### PR DESCRIPTION
**Pull request by abonas**

### CODE REVIEW

**Review by aljesusg — APPROVED** [review]
LGFM

**Comment by aljesusg** [comment]
> @aljesusg for some reason in netlify preview I see the old text and not the one that I fixed. I'm probably missing something

Mmm. I did a checkout and works. Maybe is cached in netlify. Can we force the build again?

**Review by nrfox — APPROVED** [review]
:+1:

**Comment by nrfox** [comment]
> @aljesusg for some reason in netlify preview I see the old text and not the one that I fixed. I'm probably missing something

I don't see it under `/latest` but I do see it under `/staging`: https://deploy-preview-372--kiali.netlify.app/documentation/staging/installation-guide/#_upgrade which I believe is fine

**Comment by abonas** [comment]
@nrfox what's the difference between staging/latest? both should be fixed?

**Comment by jshaughn** [comment]
@abonas In netlify you sometimes have to manually update the link to see the correct version of the file.   /latest is just a synonym for our most recent release.  /staging is basically "Head" and is where you typically want to add new content as it will be copied to the release version during the the next release CI (which will then also become the new /latest).   If you don't add content to staging then it will only ever be present in the specific version for which it was committed.

**Comment by aljesusg** [comment]
> > @aljesusg for some reason in netlify preview I see the old text and not the one that I fixed. I'm probably missing something
> 
> I don't see it under `/latest` but I do see it under `/staging`: https://deploy-preview-372--kiali.netlify.app/documentation/staging/installation-guide/#_upgrade which I believe is fine

Yes I saw it too. I thought that maybe Alissa had something cached in her browser

**Pull request merged**
