### PR TITLE
KIALI-1332 Incorporate Kiali logo in Kiali website

### PR DESCRIPTION
**Pull request by aljesusg**
result

What do you think @theute ?

### CODE REVIEW

**Comment by abonas** [comment]
I'm not @theute  ;) 
I am missing some space around the logo (on top of it and under it), in both small and big variations.
Also, I'm unsure the color change is necessary when changing the size. The darker looks more pleasant either way.

**Comment by aljesusg** [comment]
Fail ^^ @abonas, I'll give some space, about the color change it's the style of the website in the actual version the color change so what I do?

**Comment by abonas** [comment]
@aljesusg I'm not sure I understand what you wrote above regarding the color change and the actual version, can you please clarify?

**Comment by aljesusg** [comment]
Yes sorry @abonas. In https://www.kiali.io the logo change when changing size is an effect by default in the style of the website so after change the logo this effect persist, I can remove this case if you don't want this change in the logo.

**Comment by theute** [comment]
@aljesusg  you should use the logo for light background when the logo change
http://design.jboss.org/kiali/index.htm
And yes, more space :)

**Comment by theute** [comment]
And we should remove "Service Mesh Observability" from the logo here.

**Comment by aljesusg** [comment]
I think that the light background is dark for this background @theute 
screenshot from 2018-08-29 13-14-19

**Comment by aljesusg** [comment]
Without the "Service Mesh Observability" . Do we need more space or it's fine with this?
pee

**Comment by aljesusg** [comment]
Last update . What do you think @abonas @theute ?
result

**Comment by theute** [comment]
I meant to use both IIRC, the template allows that.
Like this:
http://themes.semicolonweb.com/html/canvas/demo-hosting.html
<div id="logo">
<a href="index.html" class="standard-logo" data-dark-logo="images/logo-dark.png">Canvas Logo</a>
<a href="index.html" class="retina-logo" data-dark-logo="images/logo-dark@2x.png">Canvas Logo</a>
</div>

**Comment by aljesusg** [comment]
it's not working @theute that

**Comment by aljesusg** [comment]
@theute  It seems there is a bug for data-sticky-class="dark" so I added and else in the logo control in the js file
So when is not sticker get the correct image
```js
logo: function(){
            ...
            if( $header.hasClass('sticky-header') ) {
                if( defaultStickyLogo ){ defaultLogo.find('img').attr('src', defaultStickyLogo); }
                if( retinaStickyLogo ){ retinaLogo.find('img').attr('src', retinaStickyLogo); }
            } else {
                if( defaultDarkLogo ){ defaultLogo.find('img').attr('src', defaultLogoImg); }
			}
           ...
        },
```

**Comment by theute** [comment]
It worked for me just with: (only issue now is the text menu color)
```
--- a/layouts/partials/header.html
+++ b/layouts/partials/header.html
@@ -48,7 +48,7 @@
                </div>
                <!-- Header
 ============================================= -->
-               <header id="header" class="full-header transparent-header dark" data-sticky-class="dark">
+               <header id="header" class="full-header transparent-header" data-sticky-class="dark">
 
                        <div id="header-wrap">
 
@@ -59,7 +59,7 @@
                                        <!-- Logo
                        ============================================= -->
                                        <div id="logo">
-                                               <a href="/" class="standard-logo" data-dark-logo="/images/logo-dark.svg"><img src="/images/logo-dark.svg" alt="Kiali Logo"></a>
+                                               <a href="/" class="standard-logo" data-dark-logo="/images/logo-dark.svg"><img src="/images/logo.svg" alt="Kiali Logo"></a>
                                                <!--a href="index.html" class="retina-logo" data-dark-logo="/images/logo-dark@2x.svg"><img src="/images/logo@2x.svg" alt="Kiali Logo"></a-->
                                        </div>
                                        <!-- #logo end -->
```

screencast_08-30-2018_09 48 13 am webm

**Comment by aljesusg** [comment]
Ok, perfect so I 'll do the change thanks @theute

**Comment by aljesusg** [comment]
I did the changes.

**Comment by theute** [comment]
I'm trying to figure out why the menu text is in black now

**Comment by aljesusg** [comment]
Tha dark class in the header ^^

**Comment by theute** [comment]
I see... I made a mistake...
Header is the opposite: It should be:
`<header id="header" class="full-header transparent-header dark" data-sticky-class="not-dark">`

Any reason not to put the whole logo with text at the top ?

The logo on light background doesn't look great with our current background color, I propose to merge like this and get advice on the color we should use as header background in a separate task.

**Comment by aljesusg** [comment]
in the kiali.css line 41

.dark #header-wrap:not(.not-dark) #primary-menu>ul>li>a {
    color: #fff !important;
}

**Comment by aljesusg** [comment]
With the service mesh... text ? @theute

**Comment by theute** [comment]
Without the text, just the full kiali logo with circles and "Kiali" text

And you can also delete the old "logo" files.

**Comment by aljesusg** [comment]
I set the header like the demo and I found the attribute to change the logo correctly it's **data-sticky-logo** instead of **data-dark-logo**

And I resize the image like the canvas to let the same space. What do you think ?

result

**Comment by theute** [comment]
The logo doesn't change back for me:
screencast_08-30-2018_11 57 29 am webm

**Comment by aljesusg** [comment]
Last Update
result

**Pull request merged**
