### PR TITLE
Warning severity on KIA0104, KIA0202, KIA1101 when ALLOW_ANY

### PR DESCRIPTION
**Pull request by hhovsepy**
When meshConfig.outboundTrafficPolicy.mode is set ALLOW_ANY (or default), put Warning severity on KIA0104, KIA0202, KIA1101.

RFE https://github.com/kiali/kiali/issues/5235

### CODE REVIEW

**Review by israel-hdez — APPROVED** [review]
This is OK, although I think it will be much, much clearer if this is commented under the `Severity` header.

I don't see wrong with writing bullets under the `Severity` header. Something like:

```
#### Severity

- <i class="fas fa-times-circle"></i> Error - if OutboundTrafficPolicy.Mode is set to REGISTRY_ONLY
- <i class="fas fa-exclamation-triangle"></i> Warning - if OutboundTrafficPolicy.Mode is set to ALLOW_ANY
```

I'm approving anyway, because I'm also OK with this. So, it is up to you to do the change, if you like it.

**Comment by hhovsepy** [comment]
@israel-hdez good idea, have changed.

**Comment by israel-hdez** [comment]
@hhovsepy I think you missed the dash at the beginning of each line so that it shows as bullets. Right now it is on a single line:

image

Unless this is the format you want, perhaps do the fix?

**Comment by hhovsepy** [comment]
@israel-hdez thanks for catch, have fixed.

**Pull request merged**
