### PR TITLE
Add anchors to each section title, for better traffic forwarding

### PR DESCRIPTION
**Pull request by xeviknal**
Adding anchor links to sections. Ease the job of sharing only one section of the page.
The current scenario for me is for sharing the events form.

Closes: kiali/kiali#1526

### CODE REVIEW

**Comment by abonas** [comment]
@xeviknal is this commit containing all it should? I see a one liner change that seems to be at the bottom of the page (I could be unfamiliar with the syntax too...)

**Comment by xeviknal** [comment]
yes, with this tag, every title of section is linkable. You can click to each title and you'll get the internal link.
i.e. https://deploy-preview-186--kiali.netlify.com/contribute/#_kiali_events ,
https://deploy-preview-186--kiali.netlify.com/contribute/#_talk_with_us

**Comment by jotak** [comment]
@xeviknal I like this, but it doesn't seem to work everywhere ; e.g. not in the Documentation sub-pages

**Comment by xeviknal** [comment]
All the section titles have the anchor links now. Thanks for approaching this.

**Comment by mtho11** [comment]
Nice to see this one being done! This makes it much easier when helping someone with a specific issue so that you can send them to the exact place in the documentation.

closes: https://github.com/kiali/kiali/issues/1526

**Comment by abonas** [comment]
I tested 5 different pages, works well. merging.

**Pull request merged**
