### PR TITLE
Added note about ignoring KIA0203 in case of subset not referenced in any Virtual Service.

### PR DESCRIPTION
**Pull request by hhovsepy**
Documentation changes related to https://github.com/kiali/kiali/pull/4256

### CODE REVIEW

**Review by xeviknal — COMMENTED** [review]
I think this should be aligned with this comment: https://github.com/kiali/kiali/pull/4256/files#r691269824

**Comment by hhovsepy** [comment]
Keeping the same message but showing Info severity in case of not referenced.

**Comment by xeviknal** [comment]
@jmazzitelli there is one link reference that is broken. I think it is yours:
https://github.com/kiali/kiali.io/blob/master/content/documentation/staging/faq/installation/sidecar-injection.adoc

It is the link `(1)` talking about the CNI. It looks like the anchor link is not present anymore.

**Review by xeviknal — APPROVED** [review]
LGTM!

**Comment by jmazzitelli** [comment]
> It is the link `(1)` talking about the CNI. It looks like the anchor link is not present anymore.

looks like they got rid of that in the 1.11 version of the docs:

https://istio.io/latest/docs/setup/additional-setup/cni/#identifying-pods-requiring-traffic-redirection

should now be (just replace `latest` with `v1.10`)

https://istio.io/v1.10/docs/setup/additional-setup/cni/#identifying-pods-requiring-traffic-redirection

**Pull request merged**
