### PR TITLE
document how to add a sidecar to kiali

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/4258

netlify link: https://deploy-preview-397--kiali.netlify.app/documentation/staging/faq/#sidecar-injection

see also: https://github.com/kiali/kiali-operator/pull/388

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I confirmed that setting in the Kiali Cr does inject the sidecar.

The verify error is due to some links in the v1.34 docs that are no longer valid. We can ignore these for the purposes of this PR

**Comment by nrfox** [comment]
I see the label on my kiali pod after editing my Kiali CR but the sidecar didn't actually get injected. When I do the namespace label the sidecar injection works. Maybe something with my env?

**Comment by jmazzitelli** [comment]
> When I add the injection label to my namespace the sidecar injection works. Maybe something with my env?

Did you have canary setup or the namespae label with it disabled? Those seem to override the pod label. See:
https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy

**Comment by nrfox** [comment]
> Did you have canary setup or the namespae label with it disabled? Those seem to override the pod label. See:
> https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy

Doesn't look like it but something else must be up with my env. The label is correct and matches what's in the istio docs you linked.

**Review by nrfox — APPROVED** [review]
+1 this is good to have documented

**Pull request merged**
