### PR TITLE
tell people they need to install istio and prometheus before installing kiali

### LINKED ISSUE #4703: Add prerequisites in quick-start kiali.io to try kiali
In the https://kiali.io/docs/installation/quick-start/ section the instructions are :

1.  kubectl apply -f ${ISTIO_HOME}/samples/addons/kiali.yaml

**_We should add prerequisites to be able to use kiali like having istio and prometheus installed_**

# Error reported

https://kiali.io/docs/installation/quick-start/

kubectl apply -f ${ISTIO_HOME}/samples/addons/kiali.yaml
This gives me a Kiali pod 
kubectl get pods -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-egressgateway-5457479458-zxl6h    1/1     Running   0          22m
istio-ingressgateway-7655767668-npx92   1/1     Running   0          22m
istiod-9cbc77d98-p5kcm                  1/1     Running   0          22m
kiali-c9d6f75d5-qll62                   1/1     Running   0          20m

but I get a number of errors in the Kiali console like so
Cannot load the graph: Post "http://prometheus.istio-system:9090/api/v1/query": dial tcp: lookup prometheus.istio-system on [10.96.0.10:53](http://10.96.0.10:53/): no such host

I think the bug is in the docs as the end-user also needs to have executed

kubectl apply -f ${ISTIO_HOME}/samples/addons/prometheus.yaml

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/4703

netlify links:
* https://deploy-preview-507--kiali.netlify.app/docs/installation/quick-start/
* https://deploy-preview-507--kiali.netlify.app/docs/installation/installation-guide/prerequisites/#istio

### CODE REVIEW

**Review by aljesusg — APPROVED** [review]
LGFM

**Review by jshaughn — APPROVED** [review]
OK, good, this should have solved Burr's problems.   I probably would have preferred keeping the Service Mesh Compatibility heading at ##, because #### does not show up in the right nav.  Not a big deal.

**Review by jshaughn — COMMENTED** [review]
Mazz, let's fix a broken link here as well.  If you see this in time:

docs/configuration/istio/index.html
bad: https://kubernetes.io/docs/concepts/cluster-administration/networking/#the-kubernetes-network-model 
good: https://kubernetes.io/docs/concepts/services-networking/

**Comment by jmazzitelli** [comment]
> Mazz, let's fix a broken link here as well. If you see this in time:
> 
> docs/configuration/istio/index.html bad: https://kubernetes.io/docs/concepts/cluster-administration/networking/#the-kubernetes-network-model good: https://kubernetes.io/docs/concepts/services-networking/

that's being done here https://github.com/kiali/kiali.io/pull/508 as part of issue https://github.com/kiali/kiali/issues/4673

**Comment by jmazzitelli** [comment]
> OK, good, this should have solved Burr's problems. I probably would have preferred keeping the Service Mesh Compatibility heading at ##, because #### does not show up in the right nav. Not a big deal.

didn't realize right hand nav changed. I fixed it

**Pull request merged**
