### PR TITLE
Document additional details feature

### PR DESCRIPTION
**Pull request by jotak**

### CODE REVIEW

**Comment by jotak** [comment]
(I could not test, waiting for the CI deployment to come up)

**Review by jshaughn — COMMENTED** [review]
Content looks good although did you mean to make the changes in staging as opposed to 1.28, or perhaps add the same changes to staging?

**Comment by jmazzitelli** [comment]
> Content looks good although did you mean to make the changes in staging as opposed to 1.28, or perhaps add the same changes to staging?

Good catch - this isn't in 1.28 - we need this doc to be put in staging.

**Comment by jotak** [comment]
> Content looks good although did you mean to make the changes in staging as opposed to 1.28, or perhaps add the same changes to staging?

oops that's probably a mistake

**Comment by jotak** [comment]
@jshaughn fixed

**Review by jshaughn — APPROVED** [review]
LG

**Pull request merged**
