### PR TITLE
Add and fix contribution guide

### LINKED ISSUE #4428: [website] Contribution guidelines link leads to 404
https://kiali.io/docs/contribution-guidelines/

### PR DESCRIPTION
**Pull request by aljesusg**
Fix https://github.com/kiali/kiali/issues/4428

### CODE REVIEW

**Comment by israel-hdez** [comment]
I'm not sure about this. We are not supposed to change files under `theme/docsy`.

**Comment by aljesusg** [comment]
If we add this under /docs this will appear in the menu of "docs". I think that we don't want to have contribution guide there, right?

**Comment by israel-hdez** [comment]
> If we add this under /docs this will appear in the menu of "docs".

Yes

> I think that we don't want to have contribution guide there, right?

I'm not sure. I was told that the template should guide the structure. This is why I'm saying that, in general, changes to anything inside the `themes` folder should be rejected.

Anyway, I'll let @jshaughn to answer if it's OK to have the contribution guide under `docs`. If not, the template will need to be changed.

**Comment by jmazzitelli** [comment]
> This is why I'm saying that, in general, changes to anything inside the `themes` folder should be rejected.

Yes, in general, we need to just use the theme as it is. The whole point of why we moved to this new doc structure was so we did not have to do any customization like we had to do with the other site.  Just work with the theme we have -- put the docs as best we can in the structure we have in the theme.

**Comment by aljesusg** [comment]
Closing by https://github.com/kiali/kiali/issues/4428#issuecomment-946175334

**Pull request closed without merging**
