### PR TITLE
KIALI-2208 Adds an arrow to menus with submenus

### PR DESCRIPTION
**Pull request by josejulio**
edit: Updated screenshot with latest changes
image

Also did a small refactor to remove repeated code.

### CODE REVIEW

**Comment by aljesusg** [comment]
What do you think about to flip the arrow from icon-angle-right to icon-angle-down when the submenu is collapse @josejulio @abonas ?

**Comment by abonas** [comment]
I'm wondering if the arrow should be "down" or "left"? most of the menus are opening to the left and not down, only the main menu is opened "down"

**Comment by josejulio** [comment]
This is how it looks like with a left arrow in the submenus.

It looks strange to me.

image

**Comment by josejulio** [comment]
> What do you think about to flip the arrow from icon-angle-right to icon-angle-down when the submenu is collapse @josejulio @abonas ?

I think it looks good better if the arrow starts down and ends up to the left

peek 2019-01-14 11-50

**Comment by josejulio** [comment]
I didn't push any change related to the previous screnshots, let me know what you think

**Comment by josejulio** [comment]
Updated the code to reflect the previous gif

**Comment by josejulio** [comment]
Are there more comments or changes that this PR needs?

**Pull request merged**
