### PR TITLE
Hugo upgrade to 0.121. Docsy update

### PR DESCRIPTION
**Pull request by josunect**
- Hugo upgrade to the last version: 0.121.1: https://github.com/gohugoio/hugo/releases
- Docsy upgraded to 0.8.0: https://github.com/google/docsy/releases
- Added new type parameter to blocks/section (For the index page) 
- Added new step npm build in the theme docsy to avoid missing dependencies for postcss or fontawesome
- Included twitter as excluded urls as a workaround (Now the profile requires authentication)

 https://deploy-preview-740--kiali.netlify.app/

### CODE REVIEW

**Review by hhovsepy — APPROVED** [review]
looks good, checked all pages, no regression

**Comment by ferhoyos** [comment]
Great update @josunect, it was really needed. One question, have you updated devDependencies `autoprefixer` and `postcss-cli`? With +5000 file changes I am not able to check it (browser hangs)

**Comment by josunect** [comment]
@ferhoyos no, it was not updated.

**Comment by ferhoyos** [comment]
Ok, as we are updating kiali.io stuff, I think it would be a good moment to update them too (postcss has security vulnerability). Since the PR has been already reviewed by @hhovsepy, it can be done afterwards. 

According to docsy documentation:

Starting in [version 8 of postcss-cli](https://github.com/postcss/postcss-cli/blob/master/CHANGELOG.md), you must also separately install postcss
```
npm install -D postcss
```

**Comment by josunect** [comment]
> Ok, as we are updating kiali.io stuff, I think it would be a good moment to update them too (postcss has security vulnerability). Since the PR has been already reviewed by @hhovsepy, it can be done afterwards.
> 
> According to docsy documentation:
> 
> Starting in [version 8 of postcss-cli](https://github.com/postcss/postcss-cli/blob/master/CHANGELOG.md), you must also separately install postcss
> 
> ```
> npm install -D postcss
> ```

I've updated the version for the dev dependencies.

**Pull request merged**
