### PR TITLE
KIALI-1450 Doc: known issues

### PR DESCRIPTION
**Pull request by jotak**

### CODE REVIEW

**Comment by lucasponce** [comment]
@israel-hdez commented this in the mailing list
https://groups.google.com/forum/#!topic/kiali-dev/AfCTf3W4JBQ

Perhaps, that can be added into the document ?
(On this or in following PR, that doesn't matter).

**Comment by jotak** [comment]
@lucasponce I added a section for it. Since I didn't participate in layout discussions I just describe briefly the problem, but maybe others will want to add more details.

**Comment by lucasponce** [comment]
cc @israel-hdez to add some suggestions; or we can also merge this one and add following modifications anytime.
I am fine with any way.

**Comment by aljesusg** [comment]
We can merge and update it with additional information by the Saturn team

**Pull request merged**
