### PR TITLE
Fix Kiali description

### PR DESCRIPTION
**Pull request by abonas**
Match it to be the same as the more correct description that is in the source code readme.

### CODE REVIEW

**Comment by pilhuhn** [comment]
For this you don't need Kiali and the static graph thingy would be enough.

**Comment by theute** [comment]
I agree with Heiko, this only defines the graph, we need a better description and I agree it should match the Readme.
Maybe something as dull as "Observability console and service mesh configuration for Istio" would be clear enough for the targeted audience... Or something along those line... we can start a thread on one of the mailing lists.

**Comment by abonas** [comment]
I propose to merge it, as this is anyhow more accurate than the current description that is misleading about what microservices are doing.
And absolutely kick another duscussion about improving it.

**Comment by abonas** [comment]
@theute @pilhuhn ^^ ?

**Comment by theute** [comment]
Ok, but please start the discussion or it will be forgotten

**Pull request merged**
