### PR TITLE
Add new logging enhancements video.

### PR DESCRIPTION
**Pull request by mtho11**
Add new logging enhancements video to kiali.io

### CODE REVIEW

**Comment by lucasponce** [comment]
Videos are starting to be packed in the page:

image

There 13 videos on the main page, which looks to much.

I think it's better to put the latest (2,3 or 4) and also perhaps organize the youtube channel.

Or to link the videos with the features, but let's not populate more these sections.

But if we want to add more than 2,3 or 4, we can use a scroll section similar as the blog, otherwise user won't reach that after the videos there are more sections.

**Comment by mtho11** [comment]
Yes, @lucasponce I had the same thought. The next PR will be to add horizontal scrolling to the video sections. That sound like a good solution to you?

**Comment by lucasponce** [comment]
> Yes, @lucasponce I had the same thought. The next PR will be to add horizontal scrolling to the video sections. That sound like a good solution to you?

+1 as it's already introduced in the blog post section, it sounds good.

**Comment by jshaughn** [comment]
If possible, add titles to the videos as well, it is not always possible to know what the video is from the youtube title.

**Comment by mtho11** [comment]
I created https://github.com/kiali/kiali/issues/3164 for the above comments.

**Pull request merged**
