### PR TITLE
Adding Namespace action for Canary Upgrade

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
not sure why CI is failing

**Comment by xeviknal** [comment]
hi Mr. @hhovsepy!
We've put in place a mechanism to validate broken links in the website. It looks like the two links in log are incorrect.

The first one I guess a false positive because the link is still valid.
The second one looks like the redhat.com moved some path without preserving the redirection (really really bad SEO practice :fearful:). I found the new url though (I guess): https://www.redhat.com/es/visualize_and_secure_your_service_mess_with_rh_os_service_mesh

I'd say to change the second URL and try the rebuild to see if the first one is gone. That is my feeling.

**Comment by hhovsepy** [comment]
thank you @xeviknal it seems that link does not exist in docs
> I'd say to change the second URL and try the rebuild to see if the first one is gone. That is my feeling.

**Comment by xeviknal** [comment]
I think I found it. The event's page in the home is pulling events from an csv in the cloud. It seems that one link from there is broken. I've already change it and it should work now :)

**Comment by hhovsepy** [comment]
thank you @xeviknal

**Comment by xeviknal** [comment]
@hhovsepy this might not be the case, but I see that the backend PR doesn't have any label: https://github.com/kiali/kiali/pull/4122
We typically add the `frontend changes require`, `docs`, `backend changes required` labels in PRs just for the reviewers be more aware of related changes. It is not a 100% guarantee that `docs` issues will be reviewed though.

**Comment by hhovsepy** [comment]
> @hhovsepy this might not be the case, but I see that the backend PR doesn't have any label: [kiali/kiali#4122](https://github.com/kiali/kiali/pull/4122)
> We typically add the `frontend changes require`, `docs`, `backend changes required` labels in PRs just for the reviewers be more aware of related changes. It is not a 100% guarantee that `docs` issues will be reviewed though.

Thanks @xeviknal  I will keep in mind the labeling

**Review by lucasponce — APPROVED** [review]
It sounds ok for this first pass.

As commented, as part of the bigger effort described in https://github.com/kiali/kiali/issues/4118 I guess at some point we'll revisit these descriptions and we should add more details for the users.

But this would require a first re-structure to go top-down in the documentation.

**Pull request merged**
