### PR TITLE
Breakout compatibility tables for easier consumption by external automation

### LINKED ISSUE #5823: Consistent way to resolve Kiali version from Istio version
In reference to the [thread on Slack](https://istio.slack.com/archives/CJVRXB09F/p1675794599769689), we'd like a way to consistently determine which version of Kiali will work for a given version of Istio in an automated fasion. We were previously using the compatibility matrix that was [removed a few days ago](https://github.com/kiali/kiali/commit/a6b6fe0ecdf164d7539fc6a91c2d06468980c9d2#diff-a95cce4b184f43f541db267baeda9922b7aa186a09fd3574a79060e3ca6a702e).

I understand that maintaining this is an additional layer to y'all's release process that can easily be forgotten. The separate and more consumable markdown file sounds like a good idea @jmazzitelli.

If it would help I would be happy to throw up PRs for this though since y'all would ultimately be maintaining the docs I figure you might know better that I would how you'd like it setup.

Thanks for any help with this, and appreciate all y'all do for Kiali!

### PR DESCRIPTION
**Pull request by jshaughn**
Closes https://github.com/kiali/kiali/issues/5823

### CODE REVIEW

**Comment by jmazzitelli** [comment]
doesn't look any different than before, so that's good: https://deploy-preview-632--kiali.netlify.app/docs/installation/installation-guide/prerequisites/

files are now separate.

cc @sspaeth-r7

**Review by sspaeth-r7 — APPROVED** [review]
This is awesome, thanks so much for submitting this, especially as fast as you did. This is a huge help. The columns look great too.

**Comment by sspaeth-r7** [comment]
CC @ceastman-r7

**Comment by jshaughn** [comment]
@sspaeth-r7 OK, glad it helps.  Merging...  Let us know if any sort of tweak would help out.  Note the branch name is `staging` not `master`, here is the file: 

https://github.com/kiali/kiali.io/blob/staging/content/en/docs/Installation/installation-guide/compatibility-istio.md

**Comment by jmazzitelli** [comment]
> Note the branch name is `staging` not `master`

And when released, it will go in the `current` branch.

**Comment by sspaeth-r7** [comment]
Understood. I think the master one just continued to work thanks to GitHub aliasing the two.

**Pull request merged**
