### PR TITLE
Experimenting with a google custom search engine

### PR DESCRIPTION
**Pull request by josejulio**
Google allows you to create a custom search engine https://cse.google.es/cse/

That way, you have more options to customize the search page, for example, I added the Kiali logo out there.
The page ends up being more simple, i'm unsure if we should use it or keep the current one.

Screenshot_2019-10-11_16-47-38

### CODE REVIEW

**Comment by jshaughn** [comment]
I like how the default page includes images but this custom page makes it much more clear that you are on a site-specific search.  Can the custom page include images?

**Comment by josejulio** [comment]
> Can the custom page include images?

It does, but in a different way than google.com.

Google shows by default a mixed content All ("Todos" in the gif)
Peek 2019-10-14 09-31

While the custom search engine shows them separated, I didn't see any option to have this mixed view.
Peek 2019-10-14 09-29

**Comment by josejulio** [comment]
The interesting things I found are that they provide an API so you can include the results in your page and they provide options to change fonts and colors of the text.

**Comment by israel-hdez** [comment]
I like better this approach, because people doesn't need to worry about the "site:kiali.io" keyword. And you can also click the Kiali logo to go back to the main site :)

**Comment by jshaughn** [comment]
@josejulio @israel-hdez , so what is the consensus?  Shall we merge this change?

**Comment by josejulio** [comment]
I'm +1 on merging this :)
The search page is more personalized and less hacky (you don't get to see the site:kiali.io)

**Comment by israel-hdez** [comment]
I vote for merging.

**Comment by josejulio** [comment]
Lets merge then, we can revisit this later if we need to customize any color or revert back to default google.

**Pull request merged**
