### PR TITLE
add options to the docker run command when generating crd docs

### PR DESCRIPTION
**Pull request by jmazzitelli**
@israel-hdez @nrfox will this fix the jenkins failure?

### CODE REVIEW

**Comment by jmazzitelli** [comment]
see this for another potential fix: https://github.com/containers/podman/issues/3990#issuecomment-666469279

**Comment by israel-hdez** [comment]
Perhaps let's merge it and see if it fixes the issue on the next release?
If not, we can simply do the manual website release again, and try something else.

**Comment by jmazzitelli** [comment]
@israel-hdez @nrfox can you try this? I added the command line option to use the user's uid/gid.

I only have podman - I do not have docker. If you have docker, too, see if this works as well. Just making sure I didn't break anything.

**Comment by israel-hdez** [comment]
> @israel-hdez @nrfox can you try this?

It does not work with `docker` :-(

```
% docker run --userns=keep-id --user=$(id -ur):$(id -gr) -v ./content/en/docs/Configuration:/opt/crd-docs-generator/output:z -v ./tmp-crd-docs:/opt/crd-docs-generator/config:z quay.io/giantswarm/crd-docs-generator:0.9.0 --config /opt/crd-docs-generator/config/apigen-config.yaml  
docker: --userns: invalid USER mode.
See 'docker run --help'.
```

Hmm... see: https://github.com/docker/docker.github.io/issues/7071#issuecomment-434692747

**Comment by jmazzitelli** [comment]
OK, I removed the user stuff and kept `:z`.

**Review by israel-hdez — APPROVED** [review]
We will see if this works when the next release runs.

**Pull request merged**
