### PR TITLE
Remove developer-api (swagger)

### PR DESCRIPTION
**Pull request by mtho11**
This fixes the broken api documentation by removing it for this sprint. Next sprint, the new lighter weight  asciidoc documentation will be put into place via CI/CD (and a new npm package for parsing the swagger.json and creating the adoc file for the new api documentation).

fixes #https://github.com/kiali/kiali/issues/3290

### CODE REVIEW

**Review by cfcosta — APPROVED** [review]
LGTM as soon as the build is back together.

**Comment by mtho11** [comment]
Thanks @cfcosta

**Review by jshaughn — APPROVED** [review]
@mtho11 This looks fine.  I guess by the end of the task the entire build-swagger.sh can go away from kiali.io?   Originally I was thinking we could eliminate Developer docs for the older versions as well but I guess it's OK to keep.

The netlify issue should have been resolved but you may need to push an innoccuous change to get a rebuild.

**Comment by mtho11** [comment]
@jshaughn yes, the entire build-swagger.sh can go away since it will be hosted on github pages instead.

**Comment by mtho11** [comment]
I'll ask in the watercooler today if we want to leave the old developer API docs or delete them as well (since they are broken).

**Pull request merged**
