### PR TITLE
have travis check for broken links with htmlproofer

### LINKED ISSUE #2688: run html check tool on kiali.io docs
We need Travis to run an HTML checker tool on our docs so it can catch errors such as broken links.

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes https://github.com/kiali/kiali/issues/2688

### CODE REVIEW

**Comment by jmazzitelli** [comment]
This introduces a travis script that runs an html testing tool and will fail if there are problems in our HTML such as broken links (plus other things).

Do not merge this until we fix the current failures. There are some odd failures that are due to some Hugo generation stuff (I think) - the error is "script is empty and has no src attribute" and these are found in many places. For some reason the hugo generated docs have empty `script` tags.

There are other errors in here that may be legitimate, but I'm not sure. We need someone to spend some time going through this and fixing up our docs so these tests all pass.

**Comment by lucasponce** [comment]
Is this valid ?

**Comment by jmazzitelli** [comment]
> Is this valid ?

it was when I first wrote it - no one reviewed or approved so... :)

**Comment by jmazzitelli** [comment]
I can't even run "make install build" anymore - it fails with over 100 errors that look something like this (and yes, I did "gem install bundler:2.1.4" like it says):

```
... tons of errors like this...
ERROR 2020/07/29 10:16:50 documentation/latest/faq/graph/index.adoc: Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.1.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.1.4`.

                   |  EN   
+------------------+------+
  Pages            | 1353  
  Paginator pages  |    0  
  Non-page files   |    0  
  Static files     |  119  
  Processed images |    0  
  Aliases          |  155  
  Sitemaps         |    1  
  Cleaned          |    0  

Total in 56955 ms
make: *** [build] Error 255
```

I tried "rm -rf output/ public/ Gemfile.lock" and still get the same.

**Comment by josejulio** [comment]
> I can't even run "make install build" anymore - it fails with over 100 errors that look something like this (and yes, I did "gem install bundler:2.1.4" like it says):

I still have this repo on my machine. Switched to this branch and `make install build` runs fine on my Fedora 29.

Notice that `make install` runs [gem install bundler](https://github.com/kiali/kiali.io/blob/master/Makefile#L10). So maybe that is reverting back your bundler to whatever version is using when failing? 

```
$ make install build
...
Successfully installed bundler-2.1.4
...
```

Try `bundler --version` to check the version you have before and after running the make install.

Full output in case you can make anything out of it:

```
$ make install build
Checking Dependencies
Hugo Static Site Generator v0.37.1 linux/amd64 BuildDate: 
Gem 2.7.6
Installing AsciiDoctor
Successfully installed bundler-2.1.4
Parsing documentation for bundler-2.1.4
Done installing documentation for bundler after 2 seconds
1 gem installed
Using asciidoctor 1.5.6.1
Following files may not be writable, so sudo is needed:
  /usr/bin
  /usr/share/gems
  /usr/share/gems/build_info
  /usr/share/gems/cache
  /usr/share/gems/doc
  /usr/share/gems/extensions
  /usr/share/gems/gems
  /usr/share/gems/specifications
Using bundler 2.0.1
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
rm -rf public
sh scripts/build-swagger.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  237k  100  237k    0     0   233k      0  0:00:01  0:00:01 --:--:--  233k
[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0
Prerendering docs
Non existing security scheme referenced: authorization. Skipping

🎉 bundled successfully in: redoc-static.html (3594 KiB) [⏱ 1.134s]
hugo

                   | EN   
+------------------+-----+
  Pages            |  55  
  Paginator pages  |   0  
  Non-page files   |   0  
  Static files     | 117  
  Processed images |   0  
  Aliases          |   6  
  Sitemaps         |   1  
  Cleaned          |   0  

Total in 2785 ms
```

**Comment by jshaughn** [comment]
@josejulio thanks for checking.  Are you sure you updated master?  The number of pages seems low.  Also, it's odd that the bundler downloaded and used is different:
> Successfully installed bundler-2.1.4
> Using bundler 2.0.1

**Comment by josejulio** [comment]
> Also, it's odd that the bundler downloaded and used is different:

That's odd, not sure what's going on there.

> Are you sure you updated master?

This is my git log

```
$ git log
commit b24b1bef05ddce90fe9b98c09a37c15455270551 (HEAD -> pull_227)
Author: John Mazzitelli <mazz@redhat.com>
Date:   Wed Apr 22 12:37:26 2020 -0400

    have travis check for broken links with htmlproofer

commit 8bfd14ce9126df628d1fef41f04164eeb7771a31
Author: John Mazzitelli <mazz@redhat.com>
Date:   Wed Apr 22 11:03:23 2020 -0400

    Fix broken links, add muffet target to help detect broken links (#226)
    
    * fix operator link
    
    * add muffet make target so we can test broken links
    
    * fix some broken links reported by muffet
    
    * exclude some things that we know are OK but muffet sees as bad
    
    * final corrections

commit 007c89ba8beb133762bd8b245858beb2cb6ff76e
Author: John Mazzitelli <mazz@redhat.com>
Date:   Fri Apr 17 14:14:11 2020 -0400

    create getLatestKialiOperator redirect and change documentation to refer to the new kiali.io link (no longer git.io) (#225)

commit 6fd847d8fd7a58a6be034797c2170d68f1c90459
Author: Jay Shaughnessy <jshaughn@users.noreply.github.com>
Date:   Mon Apr 13 13:35:41 2020 -0400

    add 1.15.2 relnotes (#224)

```

**Comment by israel-hdez** [comment]
I'll close this, as #351 has been merged.

**Pull request closed without merging**
